[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
    "npm ci --production=false",
    "cd client && npm ci --production=false"
]

[phases.build]
cmds = [
    "npm run railway:build"
]

[start]
cmd = "npm run railway:start"
